time_box_main_homepage:
    pattern:  /
    defaults: { _controller: TimeBoxMainBundle:Home:index }

time_box_main_file:
    pattern:  /file
    defaults: { _controller: TimeBoxMainBundle:File:show }

time_box_main_file_upload:
    pattern:  /file/upload
    defaults: { _controller: TimeBoxMainBundle:File:upload }

time_box_main_file_versions_index:
    pattern: /file/{fileId}/versions/index
    defaults: { _controller: TimeBoxMainBundle:Versions:index}
