time_box_main_homepage:
    pattern:  /
    defaults: { _controller: TimeBoxMainBundle:Home:index }

time_box_main_file:
    pattern:  /file
    defaults: { _controller: TimeBoxMainBundle:File:show }
