time_box_main_homepage:
    pattern:  /
    defaults: { _controller: TimeBoxMainBundle:Home:index }

time_box_main_login:
    pattern:  /login
    defaults: { _controller: TimeBoxMainBundle:Home:index }

time_box_main_file_upload:
    pattern:  /file/upload/{folderId}
    defaults: { _controller: TimeBoxMainBundle:File:upload, folderId: null }
    requirements:
        folderId:  \d+

time_box_main_file_versions:
    pattern: /file/versions
    defaults: { _controller: TimeBoxMainBundle:Version:index }
    requirements:
        _method:  POST

time_box_main_file_delete:
    pattern: /file/delete
    defaults: { _controller: TimeBoxMainBundle:File:delete }
    requirements:
        _method:  POST

time_box_main_file_move:
    pattern:  /file/move
    defaults: { _controller: TimeBoxMainBundle:File:move }

time_box_main_file_deleted:
    pattern:  /file/deleted/{folderId}
    defaults: { _controller: TimeBoxMainBundle:File:show, folderId: null, isDeleted: 1 }
    requirements:
        folderId:  \d+

time_box_main_file:
    pattern:  /file/{folderId}
    defaults: { _controller: TimeBoxMainBundle:File:show, folderId: null, isDeleted: 0 }
    requirements:
        folderId:  \d+

time_box_main_folder_new:
    pattern:  /folder/new/{parentFolderId}
    defaults: { _controller: TimeBoxMainBundle:Folder:new, parentFolderId: null }
    requirements:
        parentFolderId:  \d+
